# Generated by Django 4.2.7 on 2024-02-07 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_doctormodel'),
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('token', models.PositiveIntegerField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userapp.departmentmodel')),
                ('doct', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userapp.doctormodel')),
            ],
        ),
    ]
