# Generated by Django 4.2.7 on 2024-03-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_booking_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
