# Generated by Django 4.2.7 on 2024-03-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0005_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='visit',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
