# Generated by Django 4.2.7 on 2024-03-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0006_booking_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='prescription',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
