# Generated by Django 4.2.7 on 2024-02-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Departmentmodel',
        ),
    ]
