# Generated by Django 4.2.7 on 2024-02-04 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_department_departmentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctormodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=25)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.departmentmodel')),
            ],
        ),
    ]
