# Generated by Django 4.2.7 on 2024-03-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_departmentmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentmodel',
            old_name='image',
            new_name='d_image',
        ),
    ]
